"""Run the 26 analytical questions (spec 14.2) and save each result as CSV (DO-5)."""
import re
import time

from .config import OUTPUT_DIR, SQL_DIR
from .db import query

ANSWER_DIR = OUTPUT_DIR / "sql_answers"
_HEADER = re.compile(r"^-- (Q\d{2}[a-z]?)\. (.+)$", re.MULTILINE)


def parse_questions(path=SQL_DIR / "07_analytical_questions.sql"):
    """Split the query file on its '-- Qnn. title' headers -> [(qid, title, sql)]."""
    text = path.read_text(encoding="utf-8")
    heads = list(_HEADER.finditer(text))
    out = []
    for i, h in enumerate(heads):
        end = heads[i + 1].start() if i + 1 < len(heads) else len(text)
        sql = text[h.end():end].strip().rstrip(";")
        out.append((h.group(1), h.group(2).strip(), sql))
    return out


def run(verbose=True):
    ANSWER_DIR.mkdir(parents=True, exist_ok=True)
    index = []
    for qid, title, sql in parse_questions():
        start = time.perf_counter()
        df = query(sql)
        secs = time.perf_counter() - start
        if "customer_id" in df.columns:          # spec 26: masked IDs in published outputs
            df["customer_id"] = df["customer_id"].map(lambda c: c[:2] + "***" + c[-3:])
        df.to_csv(ANSWER_DIR / f"{qid}.csv", index=False)
        index.append((qid, title, len(df), secs))
        if verbose:
            print(f"  {qid:<4} {len(df):>5} rows  {secs:5.2f}s  {title[:70]}")
    lines = ["| Question | Title | Rows | Seconds |", "|---|---|---|---|"]
    lines += [f"| {q} | {t} | {n} | {s:.2f} |" for q, t, n, s in index]
    (ANSWER_DIR / "README.md").write_text(
        "# SQL answers\n\nGenerated by `python -m c360.sql_answers` from "
        "`sql/07_analytical_questions.sql`.\n\n" + "\n".join(lines) + "\n", encoding="utf-8")
    return index


if __name__ == "__main__":
    run()
