table agg_hour_weekday
	lineageTag: 7034b9d4-c049-56ae-a5ff-57cf75fa1934

	column day_of_week_num
		dataType: int64
		formatString: #,0
		lineageTag: 2508b841-fc23-551f-8430-ad4a7585b23e
		summarizeBy: none
		sourceColumn: day_of_week_num

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: string
		lineageTag: 37fd23c1-377e-5f8a-b439-b5c734daab45
		summarizeBy: none
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column txn_hour
		dataType: int64
		formatString: #,0
		lineageTag: 6c6de41a-4fe4-5863-b0a4-060ad1454c38
		summarizeBy: none
		sourceColumn: txn_hour

		annotation SummarizationSetBy = Automatic

	column txns
		dataType: int64
		formatString: #,0
		lineageTag: c1873ac7-2b35-5973-b02d-f06eca04a949
		summarizeBy: sum
		sourceColumn: txns

		annotation SummarizationSetBy = Automatic

	column total_value
		dataType: double
		formatString: #,0.00
		lineageTag: 0325c80c-0b3e-530d-b45a-2f5252dc5755
		summarizeBy: sum
		sourceColumn: total_value

		annotation SummarizationSetBy = Automatic

	partition agg_hour_weekday = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "agg_hour_weekday.csv"), [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"day_of_week_num", Int64.Type}, {"day_of_week", type text}, {"txn_hour", Int64.Type}, {"txns", Int64.Type}, {"total_value", type number}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
