table row_waterfall
	lineageTag: 1f52eb62-3d14-5afa-a0c0-d66473e05a31

	column step_no
		dataType: int64
		formatString: #,0
		lineageTag: d730722a-7ca9-5cf0-84c7-d3592bad55aa
		summarizeBy: none
		sourceColumn: step_no

		annotation SummarizationSetBy = Automatic

	column step
		dataType: string
		lineageTag: f0653d5e-c535-528a-8ba3-39e2a823aa64
		summarizeBy: none
		sourceColumn: step

		annotation SummarizationSetBy = Automatic

	column rows
		dataType: int64
		formatString: #,0
		lineageTag: bdb45158-fd92-5f66-a882-27fdebc73e37
		summarizeBy: sum
		sourceColumn: rows

		annotation SummarizationSetBy = Automatic

	partition row_waterfall = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "row_waterfall.csv"), [Delimiter = ",", Columns = 3, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"step_no", Int64.Type}, {"step", type text}, {"rows", Int64.Type}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
