table segment_definition
	lineageTag: c0ab6a22-88c1-5753-9e0b-8fed7432c3a8

	column cluster_key
		dataType: string
		isHidden
		lineageTag: 97034ed5-104e-5de3-89ff-3e956f268bae
		summarizeBy: none
		sourceColumn: cluster_key

		annotation SummarizationSetBy = Automatic

	column segment_id
		dataType: int64
		formatString: #,0
		lineageTag: 7455a095-88be-5672-97a3-f22aeb415ad7
		summarizeBy: none
		sourceColumn: segment_id

		annotation SummarizationSetBy = Automatic

	column segment_name
		dataType: string
		lineageTag: 2ff10867-f1d6-516f-8e9e-c0e546d7ae0f
		summarizeBy: none
		sourceColumn: segment_name

		annotation SummarizationSetBy = Automatic

	column customer_characteristics
		dataType: string
		lineageTag: cd5a98e6-33ad-5558-9604-9a248a84cee7
		summarizeBy: none
		sourceColumn: customer_characteristics

		annotation SummarizationSetBy = Automatic

	column transaction_characteristics
		dataType: string
		lineageTag: 18d77a8e-ad59-5603-bfda-a9eca0daf10d
		summarizeBy: none
		sourceColumn: transaction_characteristics

		annotation SummarizationSetBy = Automatic

	column financial_behaviour
		dataType: string
		lineageTag: 9e40a681-52a7-502c-a266-d5b744768ada
		summarizeBy: none
		sourceColumn: financial_behaviour

		annotation SummarizationSetBy = Automatic

	column potential_needs
		dataType: string
		lineageTag: ec82ca79-f61e-57c6-910d-3774aba2d070
		summarizeBy: none
		sourceColumn: potential_needs

		annotation SummarizationSetBy = Automatic

	column action
		dataType: string
		lineageTag: 6ec7a407-b857-5086-9305-ed7f245892b5
		summarizeBy: none
		sourceColumn: action

		annotation SummarizationSetBy = Automatic

	column owner
		dataType: string
		lineageTag: 52f86faa-8385-55da-8675-d759376b8f38
		summarizeBy: none
		sourceColumn: owner

		annotation SummarizationSetBy = Automatic

	column timing
		dataType: string
		lineageTag: 9163ba9e-9420-5725-9e96-7ae7baa9038e
		summarizeBy: none
		sourceColumn: timing

		annotation SummarizationSetBy = Automatic

	column kpi
		dataType: string
		lineageTag: 4451f17d-1982-50bd-9fd5-1597ce4bcd76
		summarizeBy: none
		sourceColumn: kpi

		annotation SummarizationSetBy = Automatic

	column expect
		dataType: string
		isHidden
		lineageTag: a5206e6e-17e6-588a-8272-3282459f13bd
		summarizeBy: none
		sourceColumn: expect

		annotation SummarizationSetBy = Automatic

	column run_id
		dataType: string
		isHidden
		lineageTag: d389930f-02e7-502f-a1d4-ec9042935b39
		summarizeBy: none
		sourceColumn: run_id

		annotation SummarizationSetBy = Automatic

	partition segment_definition = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "segment_definition.csv"), [Delimiter = ",", Columns = 13, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"cluster_key", type text}, {"segment_id", Int64.Type}, {"segment_name", type text}, {"customer_characteristics", type text}, {"transaction_characteristics", type text}, {"financial_behaviour", type text}, {"potential_needs", type text}, {"action", type text}, {"owner", type text}, {"timing", type text}, {"kpi", type text}, {"expect", type text}, {"run_id", type text}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
